# These are supported funding model platforms

github: [prathamesh424]
# patreon: # Replace with patreon username
# open_collective: # Replace with open_collective username
# ko_fi: # Replace with ko_fi username
# custom: ["https://www.buymeacoffee.com/your-username"]
